### ISSUE TITLE
Need URGENT Help in this issue "Missing APOC Core plugin"

### ISSUE THREAD

**Issue by debrupf2946** [neo4j/NaLLM#82]
I have follwing the instructions in Readme.md for setting up the docker image to run the project but I am getting "Missing APOC Core plugin" error ,please help me with solving the issue I URGENTLY need this project

Device:MAC

I set up the .env file by the downloaded txt file while setting up AuraDB 
- copied the URL,password,username,Instance01 from the txt file and annotated in .env file

```
api  | INFO:     Will watch for changes in these directories: ['/api']
api  | INFO:     Uvicorn running on http://0.0.0.0:7860 (Press CTRL+C to quit)
api  | INFO:     Started reloader process [1] using StatReload
ui   | 
ui   | > nallm-ui@1.0.0 preview
ui   | > vite preview
ui   | 
ui   |   ➜  Local:   http://localhost:4173/
ui   |   ➜  Network: http://172.18.0.2:4173/
api  | Process SpawnProcess-1:
api  | Traceback (most recent call last):
api  |   File "/api/src/driver/neo4j.py", line 70, in __init__
api  |     self.refresh_schema()
api  |   File "/api/src/driver/neo4j.py", line 116, in refresh_schema
api  |     node_props = [el["output"] for el in self.query(node_properties_query)]
api  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/api/src/driver/neo4j.py", line 116, in <listcomp>
api  |     node_props = [el["output"] for el in self.query(node_properties_query)]
api  |                   ~~^^^^^^^^^^
api  | KeyError: 'output'
api  | 
api  | During handling of the above exception, another exception occurred:
api  | 
api  | Traceback (most recent call last):
api  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
api  |     self.run()
api  |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
api  |     self._target(*self._args, **self._kwargs)
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
api  |     target(sockets=sockets)
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
api  |     return asyncio.run(self.serve(sockets=sockets))
api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
api  |     return runner.run(main)
api  |            ^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
api  |     return self._loop.run_until_complete(task)
api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
api  |     return future.result()
api  |            ^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
api  |     config.load()
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
api  |     self.loaded_app = import_from_string(self.app)
api  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
api  |     module = importlib.import_module(module_str)
api  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
api  |     return _bootstrap._gcd_import(name[level:], package, level)
api  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
api  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
api  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
api  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
api  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
api  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
api  |   File "/api/src/main.py", line 43, in <module>
api  |     neo4j_connection = Neo4jDatabase(
api  |                        ^^^^^^^^^^^^^^
api  |   File "/api/src/driver/neo4j.py", line 72, in __init__
api  |     raise ValueError("Missing APOC Core plugin")
api  | ValueError: Missing APOC Core plugin
api  | Failed to write data to connection ResolvedIPv4Address(('34.126.64.110', 7687)) (ResolvedIPv4Address(('34.126.64.110', 7687)))
api  | Failed to write data to connection IPv4Address(('eaa50530.databases.neo4j.io', 7687)) (ResolvedIPv4Address(('34.126.64.110', 7687)))
```

**Comment by gjyotin305** [comment]
I am also having this issue

**Comment by gjyotin305** [comment]
Did you find any fix ??

**Comment by tjiahen** [comment]
same issue too

**Comment by tjiahen** [comment]
Just follow this tutorial to install APOC plugin 
https://neo4j.com/labs/apoc/4.1/installation/

**Comment by gjyotin305** [comment]
Thanks @wizztjh
